CREATE TABLE visitante
(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	nome VARCHAR(50) NOT NULL,
	idade INT NOT NULL,
	entrada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	saida TIMESTAMP,
        PRIMARY KEY (id)
);

